# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy WAR app to Azure Web App - MWO-TGL-SBX-POC

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: suisei-cn/actions-download-file@v1
        id: downloadfile  # Remember to give an ID if you need the output filename
        name: Download the file
        with:
          url: "https://tomcat.apache.org/tomcat-8.5-doc/appdev/sample/sample.war"
          target: build/libs
          
#      - uses: actions/checkout@master
#      - name: copy file
#        uses: canastro/copy-file-action@master
#        with:
#          source: "build/libs/sample.war"
#          target: "wars/sample.war"

      - uses: actions/download-artifact@v2
        with:
          name: Download the file
          path: ~/wars/
